name: Lint

on:
  pull_request:
    types: opened
  push:
    paths:
      - .github/workflows/main.yml
      - go.*
      - '**.go'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.2

      - name: Setup Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.21.0
          
      - name: Lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: latest
